### ISSUE TITLE
The Started Playing message shouldn't tag the requester

### ISSUE THREAD

**Issue by andrewOOP** [Dev-Yukine/Senpai-Bot-Discord#1]
Many of my users are finding it annoying how, when the bot starts playing a requested song, it tags them, as many of my users are adding in 10+ songs at a time. They don't want to be notified of every single one of them.

Easy way to fix would be to remove the @ symbol
"Start playing: Motivational Video Game Music #13 Victory Road Requested by @User"
becomes
"Start playing: Motivational Video Game Music #13 Victory Road Requested by User"

**Comment by Dev-Yukine** [comment]
understandable will be fixed in next commit in 1 hour

**Comment by andrewOOP** [comment]
Thanks for the quick response! Really appreciate it :)
I typically don't like to use GitHub's issue tracker for suggestions. Do you have any other place to make suggestions?

**Comment by Dev-Yukine** [comment]
if you want i could add a Server for support/suggestions for the community would be an good idea i guess :thinking:

**Comment by andrewOOP** [comment]
I think that'd be a good idea 👍

**Comment by andrewOOP** [comment]
Send me a link if you decide to :)

**Comment by Dev-Yukine** [comment]
So sorry had something to do but i will give you the Invite Link and also fix this thing (your freinds can also join if they want and suggest new features/improvements) https://discord.gg/7hmMuXR

**Comment by Dev-Yukine** [comment]
also if you now how to code in JS feel free to improve/add new features and add an pull request :D

**Comment by Dev-Yukine** [comment]
fixed with https://github.com/Dev-Yukine/Senpai-Bot-Discord/commit/1bb35cecc5fa117e00254b6996692ada65ddbbfa
